### ISSUE TITLE
com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT: not found

### ISSUE THREAD

**Issue by kim6515516** [geeksville/arduleader#172]
kim6515516@kim6515516-All-Series:~/development/arduleader$ sbt
Detected sbt version 0.12.1
Starting sbt: invoke with -help for other options
[info] Loading project definition from /home/kim6515516/development/arduleader/project
[info] Set current project to scalafly (in build file:/home/kim6515516/development/arduleader/)
[info] Set current project to andropilot (in build file:/home/kim6515516/development/arduleader/)

> compile
> [info] Updating {file:/home/kim6515516/development/arduleader/}gcommon...
> [info] Wrote /home/kim6515516/development/arduleader/andropilot/target/scala-2.10/src_managed/main/scala/com/geeksville/andropilot/TR.scala
> [info] Resolving com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT ...
> [warn]  module not found: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT
> [warn] ==== local: tried
> [warn]   /home/kim6515516/.ivy2/local/com.typesafe.akka/akka-actor_2.10/2.4-SNAPSHOT/ivys/ivy.xml
> [warn] ==== Typesafe Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/akka/akka-actor_2.10/2.4-SNAPSHOT/akka-actor_2.10-2.4-SNAPSHOT.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.10/2.4-SNAPSHOT/akka-actor_2.10-2.4-SNAPSHOT.pom
> [info] Resolving com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT ...
> [warn]  module not found: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT
> [warn] ==== local: tried
> [warn]   /home/kim6515516/.ivy2/local/com.typesafe.akka/akka-slf4j_2.10/2.4-SNAPSHOT/ivys/ivy.xml
> [warn] ==== Typesafe Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/akka/akka-slf4j_2.10/2.4-SNAPSHOT/akka-slf4j_2.10-2.4-SNAPSHOT.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.10/2.4-SNAPSHOT/akka-slf4j_2.10-2.4-SNAPSHOT.pom
> [info] Resolving net.sandrogrzicic#scalabuff-compiler_2.10;1.3.7 ...
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT: not found
> [warn]  :: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [trace] Stack trace suppressed: run last gcommon/_:update for the full output.
> [error](gcommon/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT: not found
> [error] unresolved dependency: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT: not found
> [error] Total time: 3 s, completed Nov 28, 2014 9:02:21 PM
> exit
> kim6515516@kim6515516-All-Series:~/development/arduleader$ 
> kim6515516@kim6515516-All-Series:~/development/arduleader$ 
> kim6515516@kim6515516-All-Series:~/development/arduleader$ sbt
> Detected sbt version 0.12.1
> Starting sbt: invoke with -help for other options
> [info] Loading project definition from /home/kim6515516/development/arduleader/project
> [info] Set current project to scalafly (in build file:/home/kim6515516/development/arduleader/)
> [info] Set current project to andropilot (in build file:/home/kim6515516/development/arduleader/)
> project posixpilot
> [info] Set current project to posixpilot (in build file:/home/kim6515516/development/arduleader/)
> compile
> [info] Updating {file:/home/kim6515516/development/arduleader/}gcommon...
> [info] Resolving com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT ...
> [warn]  module not found: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT
> [warn] ==== local: tried
> [warn]   /home/kim6515516/.ivy2/local/com.typesafe.akka/akka-actor_2.10/2.4-SNAPSHOT/ivys/ivy.xml
> [warn] ==== Typesafe Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/akka/akka-actor_2.10/2.4-SNAPSHOT/akka-actor_2.10-2.4-SNAPSHOT.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.10/2.4-SNAPSHOT/akka-actor_2.10-2.4-SNAPSHOT.pom
> [info] Resolving com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT ...
> [warn]  module not found: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT
> [warn] ==== local: tried
> [warn]   /home/kim6515516/.ivy2/local/com.typesafe.akka/akka-slf4j_2.10/2.4-SNAPSHOT/ivys/ivy.xml
> [warn] ==== Typesafe Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/akka/akka-slf4j_2.10/2.4-SNAPSHOT/akka-slf4j_2.10-2.4-SNAPSHOT.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.10/2.4-SNAPSHOT/akka-slf4j_2.10-2.4-SNAPSHOT.pom
> [info] Resolving net.sandrogrzicic#scalabuff-compiler_2.10;1.3.7 ...
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT: not found
> [warn]  :: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [trace] Stack trace suppressed: run last gcommon/_:update for the full output.
> [error](gcommon/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.10;2.4-SNAPSHOT: not found
> [error] unresolved dependency: com.typesafe.akka#akka-slf4j_2.10;2.4-SNAPSHOT: not found
> [error] Total time: 3 s, completed Nov 28, 2014 9:03:04 PM

**Comment by horizonchasers** [comment]
kim6515516 How did you solve it? I am running into this problem and can't figure out what I am doing wrong.  Adding resolvers didn't fix it for me.

**Comment by kim6515516** [comment]
this is my diff , commit is 243a7b8f86c6d86f537b6ed75098a5ead3dc8c67



diff --git a/.gitmodules b/.gitmodules
index 4a8dfe9..9343767 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -3,4 +3,4 @@
 	url = git://github.com/geeksville/scandroid.git
 [submodule "droneapi-protobuf"]
 	path = droneapi-protobuf
-	url = git@github.com:diydrones/droneapi-protobuf.git
+	url = https://github.com/diydrones/droneapi-protobuf.git
diff --git a/andropilot/build.sbt b/andropilot/build.sbt
index 094c540..ee0d576 100644
--- a/andropilot/build.sbt
+++ b/andropilot/build.sbt
@@ -10,7 +10,7 @@ net.virtualvoid.sbt.graph.Plugin.graphSettings
 
 // Github.settings
 
-libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.2.3"
+//libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.2.3"
 
 libraryDependencies += "google-play-services" % "google-play-services_2.10" % "0.1-SNAPSHOT" artifacts(Artifact("google-play-services_2.10", "apklib", "apklib"))
 
@@ -26,6 +26,12 @@ keyalias in Android := "geeksville-android-key"
 
 keystorePath in Android := file("andropilot/geeksville-release-key.keystore")
 
+resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"
+
+libraryDependencies +=  "com.typesafe.akka" % "akka-actor_2.10" % "2.4-SNAPSHOT"
+
+libraryDependencies += "com.typesafe.akka" % "akka-slf4j_2.10" % "2.4-SNAPSHOT"
+
 //signRelease in Android <<= signReleaseTask
 
 //signRelease in Android <<= (signRelease in Android) dependsOn (packageRelease in Android)
diff --git a/build.sbt b/build.sbt
index 2c9e4e1..adcbeda 100644
--- a/build.sbt
+++ b/build.sbt
@@ -8,6 +8,8 @@ resolvers += "Typesafe Repository" at "http://repo.typesafe.com/typesafe/release
 
 net.virtualvoid.sbt.graph.Plugin.graphSettings
 
+libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.2-SNAPSHOT"
+
 libraryDependencies += "org.scala-lang" % "scala-compiler" % "2.10.4" withSources()
 
 libraryDependencies += "org.scala-lang" % "jline" % "2.10.4" withSources()
@@ -21,3 +23,10 @@ EclipseKeys.createSrc in ThisBuild := EclipseCreateSrc.Default + EclipseCreateSr
 EclipseKeys.withSource in ThisBuild := true // Try to include source for libs
 
 EclipseKeys.relativizeLibs in ThisBuild := false // Doesn't seem to work for lib directory
+
+resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"
+
+libraryDependencies +=  "com.typesafe.akka" % "akka-actor_2.10" % "2.4-SNAPSHOT"
+
+libraryDependencies += "com.typesafe.akka" % "akka-slf4j_2.10" % "2.4-SNAPSHOT"
+
diff --git a/common/build.sbt b/common/build.sbt
index a78bdd3..2cb83b8 100644
--- a/common/build.sbt
+++ b/common/build.sbt
@@ -6,9 +6,9 @@ resolvers += "Typesafe Repository" at "http://repo.typesafe.com/typesafe/release
 
 scalacOptions in ThisBuild ++= Seq("-unchecked", "-deprecation", "-optimise") // , "-feature"
 
-libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.4-SNAPSHOT"
+//libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.4-SNAPSHOT"
 
-libraryDependencies += "com.typesafe.akka" %% "akka-slf4j" % "2.4-SNAPSHOT"
+//libraryDependencies += "com.typesafe.akka" %% "akka-slf4j" % "2.4-SNAPSHOT"
 
 unmanagedResourceDirectories in Compile <+= baseDirectory( _ / "src" / "main" / "scala" )
 
@@ -21,3 +21,12 @@ libraryDependencies += "net.sandrogrzicic" %% "scalabuff-runtime" % "1.3.7" with
 libraryDependencies += "com.google.protobuf" % "protobuf-java" % "2.5.0" withSources()
 
 libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.0" % "test"
+
+
+resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"
+
+libraryDependencies +=  "com.typesafe.akka" % "akka-actor_2.10" % "2.4-SNAPSHOT"
+
+libraryDependencies += "com.typesafe.akka" % "akka-slf4j_2.10" % "2.4-SNAPSHOT"
+
+
diff --git a/posixpilot/build.sbt b/posixpilot/build.sbt
index ef0f6c1..ec83788 100644
--- a/posixpilot/build.sbt
+++ b/posixpilot/build.sbt
@@ -14,9 +14,18 @@ libraryDependencies += "net.java.dev.jna" % "jna" % "3.5.1" // For libFtdi
 
 libraryDependencies += "ch.qos.logback" % "logback-core" % "1.0.9" withSources()
 
+libraryDependencies += "com.typesafe.akka" % "akka-stream-experimental_2.10" % "0.11"
+
 EclipseKeys.createSrc := EclipseCreateSrc.Default + EclipseCreateSrc.Resource // Include resources dir in eclipse classpath
 
 EclipseKeys.withSource := true // Try to include source for libs
 
 compileOrder := CompileOrder.JavaThenScala
 
+resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"
+
+libraryDependencies +=  "com.typesafe.akka" % "akka-actor_2.10" % "2.4-SNAPSHOT"
+
+libraryDependencies += "com.typesafe.akka" % "akka-slf4j_2.10" % "2.4-SNAPSHOT"
+
+
