### ISSUE TITLE
Not responding + configure "dronshare.com" when I launched it.

### ISSUE THREAD

**Issue by GildedHonour** [geeksville/arduleader#174]
Finally I was able to compile it and when I launched it on my device, it showed the black screen and the dialog asking "it's not responding, do you want to wait or close it?". Also, it showed the notification that I configure "dronshare.com", I pressed it but nothing happened. What's the matter?

**Comment by aruvalcaba** [comment]
Did you fix this? I also am receiving the same error?

**Comment by GildedHonour** [comment]
No. I can't even compile it in Android Studio or IntelliJ.

**Comment by geeksville** [comment]
Hi guys, see the build instructions here: (it build from the command line
not the IDE) https://github.com/geeksville/arduleader/blob/master/README.md
