### ISSUE TITLE
Google Map wont show up 

### ISSUE THREAD

**Issue by danpe** [geeksville/arduleader#53]
Hey,

After compiling from source and installing the app both on Galaxy S2 and Nexus 7 everything looks good except the Google Map that just wont show up.

Maybe something went wrong when compiling google-play-service ?
How can i debug this issue?

Maybe i need to use Google API SDK when compiling ?

**Comment by aruvalcaba** [comment]
Can anyone elaborate on this? I believe I am suffering from the same problem. I tried making my own key and using the key under ANDROID_SDK_HOME/.android/debug.keystore and neither work to show the Google map.

**Comment by geeksville** [comment]
Hi @aruvalcaba - sorry, was ignoring github a bit until today.  I'll answer your other comments also...

Hmm - you should be fine if you just plug in the key registered using the google maps android api v2 console...

**Comment by aruvalcaba** [comment]
@geeksville So I should create an Google Maps V2 API key using the default debug.keystore under  the ANDROID_SDK_HOME/.android?
